### ISSUE TITLE
EPIC: Search Panel UI 2.0

### ISSUE THREAD

**Issue by TatsumiSuenaga** [TatsumiSuenaga/whatshouldieat#21]
Search Panel will be justified to the left, and be rearranged from Input Group Bootstrap component to Form to allow for the OnSubmit functionality.

**New search panel will:**
- [ ] Arrange new search fields in accordion layout
- [ ] Support rating search
- [ ] Support price search
- [x] Input Group -> Form Group
- [ ] Add/delete restaurants from search

Optional:
- [ ] Support adding new cuisines

**Comment by TatsumiSuenaga** [comment]
Changing direction, will close for a clean start
