### ISSUE TITLE
[STORY] Clean up code and implement React Hooks

### ISSUE THREAD

**Issue by TatsumiSuenaga** [TatsumiSuenaga/whatshouldieat#38]
#Description
Remove crazy nested components and create Contexts that pass data. Use hooks to use said data.

## Tasks

- [ ] Update Component architecture
- [ ] Create Context Components
- [ ] Pass data via Context Components

## Acceptance criteria
Complete said above tasks

**Comment by TatsumiSuenaga** [comment]
This does not scale. Having a single global context would cause performance issues with re-renders of every component whenever a single value is changed. 
Could have multiple contexts, but that is still not the most scalable.
Will go back to redux for now.
