### ISSUE TITLE
[TASK] Various Bug Fixes

### ISSUE THREAD

**Issue by TatsumiSuenaga** [TatsumiSuenaga/whatshouldieat#46]
#Description
Fix various non-critical bugs

## Todo

- [x] Fix wrong restaurant type issue (during results)
- [x] RestaurantNotFound issue should not be possible with the surprise me search
- [x] Fix issue where results from previous search linger (due to not proper clearing in the UserPref Search)
- [x] Remove duplicates from search list
